name = "halo"
version = "0.1.0"
description = "A Gleam project"

licences = ["Apache-2.0"]
repository = { type = "github", user = "PROMETHIA-27", repo = "halo" }

[dependencies]
gleam_stdlib = "~> 0.29"
fs = "~> 8.6"
gleam_erlang = "~> 0.19"
shellout = "~> 1.3"
tomerl = "~> 0.5"

[dev-dependencies]
gleeunit = "~> 0.10"

[mote]
bin_whitelist = [
    "erl.exe",
    "launch.escript",
    "launch.exe",
    "no_dot_erlang.boot",
]
erts_bin_whitelist = [
    "beam.smp.dll",
    "erlexec.dll",
]
lib_whitelist = [
    "compiler",
    "kernel",
    "stdlib",
]